# ===== URLs =====
app.url=https://wishlist.otus.kartushin.su
api.url=https://api.wishlist.otus.kartushin.su
swagger.url=${api.url}/swagger-ui/index.html

# ===== Browser =====
browser.type=chrome
browser.headless=false
browser.timeout=10

# ===== Test Data =====
test.user.login=student
test.user.password=student